server:
  port: 8060
server-gateway:
  port: ${PORT:8080}
eureka:
  client:
    serviceUrl:
      defaultZone: https://secret-anchorage-03030.herokuapp.com/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: openapi
          uri: https://fast-lake-01538.herokuapp.com
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: auth
        url: /v3/api-docs/auth

ribbon:
  ReadTimeout: 10000000
  ConnectTimeout: 10000000