server:
  port: 8060
server-gateway:
  port: ${PORT:8080}
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: https://secret-anchorage-03030.herokuapp.com/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: https://api-login-all-it.herokuapp.com/
          predicates:
            - Path=/auth/**
          filters:
#            - EncryptDecryptFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: email
          uri: https://api-email-jj.herokuapp.com/
          predicates:
            - Path=/v3/api-docs/**
          filters:
            #            - EncryptDecryptFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: openapi
          uri: https://fast-lake-01538.herokuapp.com
          predicates:
            - Path=/v3/api-docs/**
          filters:
#            - EncryptDecryptFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs


springdoc:
  swagger-ui:
    urls:
      - name: auth
        url: /v3/api-docs/auth

ribbon:
  ReadTimeout: 2147483647
  ConnectTimeout: 2147483647

niws:
  loadbalancer:
    availabilityFilteringRule:
      activeConnectionsLimit: 2147483647