
spring:
  application:
    name: gateway
server:
  port: ${PORT:8081}
  servlet:
    context-path: /gateway

server-gateway:
  port: ${PORT:8080}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: https://secret-anchorage-03030.herokuapp.com/eureka/
    fetch-registry: true
    register-with-eureka: true

zuul:
  sensitive-headers: Cookie
# Apenas assinador para aumentar a seguranca e encryptar o codigo basta retirar o type de todos servicos

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

